@echo off
start cmd.exe /k "python elasticsearch_query_comparison.py"&
start cmd.exe /k "python elasticsearch_query_comparison.py"&
start cmd.exe /k "python elasticsearch_query_comparison.py"&
start cmd.exe /k "python elasticsearch_query_comparison.py"&
start cmd.exe /k "python elasticsearch_query_comparison.py"&
start cmd.exe /k "python elasticsearch_query_comparison.py"&
start cmd.exe /k "python elasticsearch_query_comparison.py"&
start cmd.exe /k "python elasticsearch_query_comparison.py"&
start cmd.exe /k "python elasticsearch_query_comparison.py"&
start cmd.exe /k "python elasticsearch_query_comparison.py"&
start cmd.exe /k "python elasticsearch_query_comparison.py"&
start cmd.exe /k "python elasticsearch_query_comparison.py"&
start cmd.exe /k "python elasticsearch_query_comparison.py"&
start cmd.exe /k "python elasticsearch_query_comparison.py"&
start cmd.exe /k "python elasticsearch_query_comparison.py"&
start cmd.exe /k "python elasticsearch_query_comparison.py"&
start cmd.exe /k "python elasticsearch_query_comparison.py"&
start cmd.exe /k "python elasticsearch_query_comparison.py"&
start cmd.exe /k "python elasticsearch_query_comparison.py"&
start cmd.exe /k "python elasticsearch_query_comparison.py"&
start cmd.exe /k "python elasticsearch_query_comparison.py"&
start cmd.exe /k "python elasticsearch_query_comparison.py"&
start cmd.exe /k "python elasticsearch_query_comparison.py"&
start cmd.exe /k "python elasticsearch_query_comparison.py"&
start cmd.exe /k "python elasticsearch_query_comparison.py"&
start cmd.exe /k "python elasticsearch_query_comparison.py"&
start cmd.exe /k "python elasticsearch_query_comparison.py"&
start cmd.exe /k "python elasticsearch_query_comparison.py"&
start cmd.exe /k "python elasticsearch_query_comparison.py"&
start cmd.exe /k "python elasticsearch_query_comparison.py"&