JSON_TIME_FORMAT = "%Y-%m-%dT%H:%M:%S.%fZ"
SIMPLE_TIME_FORMAT = "%Y-%m-%dT%H:%M:%S%z"

# Event names for the UserActivityData table
UMR_OPEN_ARTICLE_ACTION = "UMR - OPEN ARTICLE"
UMR_OPEN_STARRED_ARTICLE_ACTION = "UMR - OPEN STARRED ARTICLE"
UMR_ARTICLE_FOCUSED_ACTION = "UMR - ARTICLE FOCUSED"
UMR_ARTICLE_CLOSED_ACTION = "UMR - ARTICLE CLOSED"

UMR_TRANSLATE_TEXT_ACTION = "UMR - TRANSLATE TEXT"
UMR_SPEAK_TEXT_ACTION = "UMR - SPEAK TEXT"
UMR_OPEN_ALTERMENU_ACTION = "UMR - OPEN ALTERMENU"
UMR_CLOSE_ALTERMENU_ACTION = "UMR - CLOSE ALTERMENU"
UMR_UNDO_TEXT_TRANSLATION_ACTION = "UMR - UNDO TEXT TRANSLATION"
UMR_SEND_SUGGESTION_ACTION = "UMR - SEND SUGGESTION"
UMR_CHANGE_ORIENTATION_ACTION = "UMR - CHANGE ORIENTATION"

UMR_LIKE_ARTICLE_ACTION = "UMR - LIKE ARTICLE"
UMR_ARTICLE_LOST_FOCUS_ACTION = "UMR - ARTICLE LOST FOCUS"
UMR_ARTICLES_REQUESTED_FROM_ZEEGUU = "UMR - ARTICLES REQUESTED FROM ZEEGUU"
