JSON_TIME_FORMAT = "%Y-%m-%dT%H:%M:%S.%fZ"
SIMPLE_TIME_FORMAT = "%Y-%m-%dT%H:%M:%S%z"

# Event names for the UserActivityData table
UMR_OPEN_ARTICLE_ACTION = "UMR - OPEN ARTICLE"
UMR_OPEN_STARRED_ARTICLE_ACTION = "UMR - OPEN STARRED ARTICLE"
UMR_ARTICLE_FOCUSED_ACTION = "UMR - ARTICLE FOCUSED"
